name: Package the latest toolbox code and release as MLTBX.

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."  
      - name: Set up MATLAB
        # This uses the latest release of MATLAB. Can specify "release" if needed.
        uses: matlab-actions/setup-matlab@v1.0.1
      - run: echo "MATLAB has been setup ${{ github.repository }}."  
      # - name: Run script
      # uses: matlab-actions/run-command@v1
      # with:
      # command: myscript
