name: Package and release MLTBX

on:
  # Automatically run this action when a new v* tag is created
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # Allows you to specify release name when running action manually
      releaseName:
        description: 'Release name'
        default: github.sha

jobs:
  my-job:
    name: Release MLTBX
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."  
      - name: Set up MATLAB
        # This uses the latest release of MATLAB. Can specify "release" if needed.
        uses: matlab-actions/setup-matlab@v1.0.1
      - name: Package mltbx
        uses: matlab-actions/run-command@v1.0.1
        with:
          # Package mltbx file. Ensure that mltbx file exists before returning.
          command: matlab.addons.toolbox.packageToolbox('newtoolbox/RVC3.prj'), assert(exist('newtoolbox/RVC3.mltbx', 'file'));
      - name: Create new release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: newtoolbox/RVC3.mltbx          
          tag_name: ${{ github.event.inputs.releaseName }}
    
